### ISSUE TITLE
Running syslog connector on a Kafka Connect-Cluster

### ISSUE THREAD

**Issue by meslami1** [jcustenborder/kafka-connect-syslog#10]
Running the syslog connector on a kaka-connect cluster that consists of more than 1 node frequently results in the message of "syslog server' already running" and results in the syslog connector not running.  

The case to reproduce is as follows:
-Stand up to 2 Connect workers that are part of the same Kafka-Connect cluster (I used docker containers on 2 separate machines)
-Create the Syslog connector (at this point, one member in the cluster will be listening on the configured port and the other won't)
-Power off the first connect worker (the second worker will take over)
-Power on the first connect worker (the connector will throw an exception with the below error message).

At this point, its not possible/stable to stand up the syslog connector across the cluster unless you make a brand new connector.  

This same case happens during "Rebalancing"; when you have 1 worker thats configured and running the connector and you add in a second worker to the same Kafka Connect cluster.

[2017-06-19 11:57:36,783] INFO Starting syslog on port 3001 (com.github.jcustenborder.kafka.connect.syslog.SyslogSourceTask)
[2017-06-19 11:57:36,784] ERROR Task Syslog-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.graylog2.syslog4j.SyslogRuntimeException: SyslogServer instance "syslog server" already defined.
        at org.graylog2.syslog4j.server.SyslogServer.throwRuntimeException(SyslogServer.java:74)
        at org.graylog2.syslog4j.server.SyslogServer.createInstance(SyslogServer.java:133)
        at org.graylog2.syslog4j.server.SyslogServer.createThreadedInstance(SyslogServer.java:161)
        at com.github.jcustenborder.kafka.connect.syslog.SyslogSourceTask.start(SyslogSourceTask.java:60)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:141)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-06-19 11:57:36,785] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2017-06-19 11:57:36,785] INFO Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer)
[2017-06-19 11:58:14,400] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect)
[2017-06-19 11:58:14,401] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer)
[2017-06-19 11:58:14,409] INFO Stopped ServerConnector@2ba45490{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector)
[2017-06-19 11:58:14,421] INFO Stopped o.e.j.s.ServletContextHandler@26f1249d{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler)
[2017-06-19 11:58:14,424] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer)
[2017-06-19 11:58:14,424] INFO Herder stopping (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
[2017-06-19 11:58:14,424] INFO Stopping connectors and tasks that are still assigned to this worker. (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
[2017-06-19 11:58:14,428] INFO Stopping task Syslog-0 (org.apache.kafka.connect.runtime.Worker)
[2017-06-19 11:58:19,425] WARN Interrupted while waiting for consumer heartbeat thread to close (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2017-06-19 11:58:19,428] ERROR Failed to close coordinator (org.apache.kafka.clients.ClientUtils)
org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeThrowInterruptException(ConsumerNetworkClient.java:417)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:263)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.maybeLeaveGroup(AbstractCoordinator.java:702)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:676)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:665)
        at org.apache.kafka.connect.runtime.distributed.WorkerCoordinator.close(WorkerCoordinator.java:294)
        at org.apache.kafka.clients.ClientUtils.closeQuietly(ClientUtils.java:67)
        at org.apache.kafka.connect.runtime.distributed.WorkerGroupMember.stop(WorkerGroupMember.java:185)
        at org.apache.kafka.connect.runtime.distributed.WorkerGroupMember.stop(WorkerGroupMember.java:134)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.halt(DistributedHerder.java:360)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:201)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
        ... 17 more
[2017-06-19 11:58:19,444] INFO Herder stopped (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
[2017-06-19 11:58:19,444] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect)
[2017-06-19 11:58:19,445] ERROR Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder)

**Comment by jcustenborder** [comment]
@meslami1 Unfortunately this isn't going to happen, you're going to need to run in standalone mode for this connector. The rebalancing algorithm does not take resources like ports into account when it places tasks.
