### ISSUE TITLE
does not work properly

### ISSUE THREAD

**Issue by evilezh** [jcustenborder/kafka-connect-syslog#7]
on first run it is fine .. but if I restart or add more syslog sinks .. i got error: 
```
org.graylog2.syslog4j.SyslogRuntimeException: SyslogServer instance "syslog server" already defined.
	at org.graylog2.syslog4j.server.SyslogServer.throwRuntimeException(SyslogServer.java:74)
	at org.graylog2.syslog4j.server.SyslogServer.createInstance(SyslogServer.java:133)
	at org.graylog2.syslog4j.server.SyslogServer.createThreadedInstance(SyslogServer.java:161)
	at com.github.jcustenborder.kafka.connect.syslog.SyslogSourceTask.start(SyslogSourceTask.java:60)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:141)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
But in general it is not much usable service. As it is hard to bind to static name/ip.

**Comment by jcustenborder** [comment]
@evilezh It works just fine. This will happen when you are trying to run more than one task on the same port.
