### ISSUE TITLE
SSLSyslog Password Verification Failed for Truststore

### ISSUE THREAD

**Issue by meslami1** [jcustenborder/kafka-connect-syslog#8]
The SSLTCPSyslog connector keeps showing "Password Verification failed"

When I use keytool directly with both truststore and keystore (using full path), the contents appear fine and keytool is able to open the truststore and keystore with the password.

Exception in thread "SyslogServer: Syslog Server" org.graylog2.syslog4j.SyslogRuntimeException: java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at org.graylog2.syslog4j.server.impl.net.tcp.TCPNetSyslogServer.run(TCPNetSyslogServer.java:195)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at javax.net.ssl.DefaultSSLServerSocketFactory.throwException(SSLServerSocketFactory.java:160)
	at javax.net.ssl.DefaultSSLServerSocketFactory.createServerSocket(SSLServerSocketFactory.java:188)
	at org.graylog2.syslog4j.server.impl.net.tcp.TCPNetSyslogServer.createServerSocket(TCPNetSyslogServer.java:175)
	at org.graylog2.syslog4j.server.impl.net.tcp.TCPNetSyslogServer.run(TCPNetSyslogServer.java:191)
	... 1 more
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.security.Provider$Service.newInstance(Provider.java:1617)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLServerSocketFactory.getDefault(SSLServerSocketFactory.java:113)
	at org.graylog2.syslog4j.server.impl.net.tcp.ssl.SSLTCPNetSyslogServer.getServerSocketFactory(SSLTCPNetSyslogServer.java:54)
	at org.graylog2.syslog4j.server.impl.net.tcp.TCPNetSyslogServer.createServerSocket(TCPNetSyslogServer.java:170)
	... 2 more
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.getDefaultKeyManager(SSLContextImpl.java:852)
	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:732)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.security.Provider$Service.newInstance(Provider.java:1595)
	... 9 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
	... 20 more

**Comment by meslami1** [comment]
Found the issue.

In SSLTCPSyslogSourceConnectorConfig.java, line 63 and 85 are casting getPassword to String (.toString).  This is causing the password to be used for the keystore to be the literal string "[hidden]" instead of the actual password.  

The fix: change .toString() to .value().  It keeps the password hidden in the logs and uses the correct password to unlock the keystore/truststore.

This is somewhat related to https://issues.apache.org/jira/browse/KAFKA-2690.

**Comment by jcustenborder** [comment]
This was fixed by you pull. Thanks!
